default: &default
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  pool: 5
  url: mysql2://root:root@127.0.0.1:3100

development:
  <<: *default
  database: personal_web_development

production:
  <<: *default
  database: personal_web_production

test:
  <<: *default
  database: personal_web_test